#!/usr/bin/perl -w
# HoneySpy -- advanced honeypot environment
# Copyright (C) 2005  Robert Nowotniak
# Copyright (C) 2005  Michal Wysokinski
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

use strict;
use Switch;
use IO::Handle;

open(LOG, '>&=3');
LOG->autoflush(1);

$| = 1;

my $komeda;
my $user="@";
my $nazwa_serwera="localhost";

print "220 $nazwa_serwera ESMTP Welcome\n";

while(defined($komeda = <STDIN>)) {
	chop $komeda;

	#musi byc poza switchem bo w casie w znakach {} nie widac juz zmiennej $1
	#czyzby kazdy blok mial wlasna?
	if($komeda =~ /^MAIL FROM: *(<.*>)$/i) {
		print "554 5.7.1 $1 : Sender address rejected:\n";	
	}

	switch($komeda){	
		case "" { print "500 5.5.2 Error: bad syntax\n";}

		case /^HELO$/	{
			print "501 Syntax: HELO hostname\n";
		}

		case /^HELO /i    {
			print "250 $nazwa_serwera\n";
		}

		case /^EHLO$/  {
			print "501 Syntax: EHLO hostname\n";
		}

		case /^EHLO /i {
			print <<EOF
			250-$nazwa_serwera
			250-PIPELINING
			250-SIZE 30000000
			250-VRFY
			250-ETRN
			250-STARTTLS
			250-AUTH PLAIN LOGIN
			250-AUTH=PLAIN LOGIN
			250-ENHANCEDSTATUSCODES
			250-8BITMIME
			250 DSN
EOF
		}

		case /^QUIT$/i {
			print "221 2.0.0 Bye\n";
			exit 0;
		}

		case /^MAIL FROM:$/i {
			print "501 5.5.4 Syntax: MAIL FROM:<address>\n";
		}

		else {
			print "502 5.5.2 Error: command not recognized\n";
			print LOG "Client run SMTP command: $komeda\n";
		}
	}
}
